# Generated by Django 6.0.6 on 2026-07-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=20)),
                ('icon', models.ImageField(upload_to='')),
                ('skill_percentage', models.IntegerField()),
                ('skill_description', models.TextField()),
            ],
        ),
    ]
