# Generated by Django 6.0.6 on 2026-07-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='icon',
            field=models.ImageField(upload_to='skills/'),
        ),
    ]
