# Generated by Django 6.0.6 on 2026-07-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_skills_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('pro_description', models.TextField()),
                ('pro_image', models.ImageField(upload_to='projects/')),
                ('git_link', models.URLField()),
                ('live_link', models.URLField(blank=True)),
                ('tool', models.ManyToManyField(related_name='projects', to='myapp.tool')),
            ],
        ),
    ]
