# Generated by Django 6.0.6 on 2026-07-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tool_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eduacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=40)),
                ('institute', models.CharField(max_length=30)),
                ('edu_description', models.TextField()),
            ],
        ),
    ]
