# Generated by Django 6.0.6 on 2026-07-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='paragraph2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='paragraph3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
