# Generated by Django 6.0.6 on 2026-07-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_about_paragraph2_alter_about_paragraph3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_icon', models.ImageField(upload_to='services/icon')),
                ('ser_name', models.CharField(max_length=20)),
                ('ser_desc', models.TextField()),
                ('li1', models.CharField(max_length=30)),
                ('li2', models.CharField(blank=True, max_length=30, null=True)),
                ('li3', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
