# Generated by Django 6.0.6 on 2026-07-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplaySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='display_skill',
            field=models.ManyToManyField(related_name='display_skills', to='myapp.displayskills'),
        ),
    ]
