# Generated by Django 6.0.6 on 2026-07-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_displayskills_home_display_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduacation',
            name='course',
            field=models.CharField(max_length=100),
        ),
    ]
