# Generated by Django 6.0.6 on 2026-07-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_eduacation_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='ser_name',
            field=models.CharField(max_length=50),
        ),
    ]
